const ContextTypes = {
  DISPLAY_MENU: "DISPLAY_MENU",
  CHANGE_FILTER: "CHANGE_FILTER",
  SET_FILTER_FROM_QUERY: "SET_FILTER_FROM_QUERY",
  SET_SORT_STATE: "SET_SORT_STATE"
};
export default ContextTypes;
